#!/bin/bash


setup_color() {
	# Only use colors if connected to a terminal
	if [ -t 1 ]; then
		RED=$(printf '\033[31m')
		GREEN=$(printf '\033[32m')
		YELLOW=$(printf '\033[33m')
		BLUE=$(printf '\033[34m')
		BOLD=$(printf '\033[1m')
		RESET=$(printf '\033[m')
	else
		RED=""
		GREEN=""
		YELLOW=""
		BLUE=""
		BOLD=""
		RESET=""
	fi
}

# install deb packages
PACKAGES=$(cat .packages | grep -ve '^#')
printf "${GREEN}> Installing the following packages:${RESET}\n\n"
printf "#################\n"
printf "$PACKAGES\n"
printf "#################\n\n"
sudo apt-get update > /dev/null
sudo apt-get install -y $PACKAGES > /dev/null

# make zsh defautl browser
printf "${GREEN}> Installing zsh shell...${RESET}\n"
sudo apt install zsh
printf "${GREEN}> Installed zsh version: $(zsh --version)${RESET}\n"
printf "${GREEN}> Configuring zsh as the default shell for user: $USER${RESET}\n"
chsh -s $(which zsh)

snap install codium --classic
stow vscodium zsh

# powerline fonts
# Now please install brave
# curl then dpkg -i

# alias xapt="apt"