# bash bootstrap.sh --profile=pro --theme=powerline9k --plugins=git,docker...

# -p --profile  :       pro, personal
# -t --theme    :       powerlinek, agnoster,...
#    --plugins  :       git, docker, ruby, virtualenv,...
# -f --fonts    :       font-awesome,...
# -a --aliases  :       ./myaliases
