#!/bin/sh

alias plz="sudo"

# changing/making/removing directory
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

alias d="dirs -v | head -10"
alias ...="../.."
alias ....="../../.."
alias .....="../../../.."
alias ......="../../../../.."
alias -- -="cd -"
alias 1="cd -"
alias 2="cd -2"
alias 3="cd -3"
alias 4="cd -4"
alias 5="cd -5"
alias 6="cd -6"
alias 7="cd -7"
alias 8="cd -8"
alias 9="cd -9"

# list directory contents
alias lsa="ls -lah"
alias l="ls -lah"
alias ll="ls -lh"
alias la="ls -lAh"

# push and pop directories on directory stack
alias pu="pushd"
alias po="popd"

# make some commands less destructive
alias rm="rm -i"

# custom projects
alias xw="cd $HOME/projects/iexec/xtremweb"
alias downloads="cd $HOME/Downloads"
